
name: Build NACCM

on:
  workflow_dispatch
 
jobs:
  build:

    runs-on: windows-2019
          
    steps:

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
	with:
    	  msbuild-architecture: x64
     
    - name: Checkout Code
      uses: actions/checkout@master
            
    - name: Build App
      run: msbuild ${{env.GITHUB_WORKSPACE}}\NACCM\NACCM.sln /p:Configuration=Release /p:DeployOnBuild=false -verbosity:diag


        
