
name: Build NACCM

on:
  workflow_dispatch
 
jobs:
  build:

    runs-on: windows-2019
          
    steps:

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
	with:
    	  msbuild-architecture: x64
     
    - name: Checkout Code
      uses: actions/checkout@master
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore NACCM.sln
      

      
    - name: Build and Publish Web App
      run: msbuild NACCM.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Build app for release
  run: msbuild src\YourProjectFile.csproj -t:rebuild -verbosity:diag -property:Configuration=Release


    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp


        
