name: Build NACCM

on:
  workflow_dispatch: 
 
jobs:
  build:

    runs-on: windows-2019 
          
    steps:
      - uses: actions/checkout@v3
       
      - uses: microsoft/setup-msbuild@v1
        with:
           msbuild-architecture: x64
           
      - name: Navigate to workspace
        run: cd $GITHUB_WORKSPACE

      - name: Create a build directory
        run: mkdir _build

      - name: Restore Packages
        run: nuget restore ${{ github.workspace }}\NACCM\naccm.sln

      - name: gac dependency
        run: gacutil /i ${{ github.workspace }}\ApplicationStartup\obj\ServiceLogging.dll

      - name: Build App
        run: msbuild ${{ github.workspace }}\NACCM\naccm.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="PRDAPP3WithPRDDB3" /p:PublishUrl="../_build"

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
           name: Build Output
           path: "./_build"
   
